[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][ValidateSet('Touch','Led')][string]$Component,
    [Parameter(Mandatory = $true)][string]$InstallRoot,
    [string]$DataRoot = (Join-Path $env:ProgramData 'TG Exhibition'),
    [string]$SiteConfig
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Security
$install = [IO.Path]::GetFullPath($InstallRoot)
$data = [IO.Path]::GetFullPath($DataRoot)
$configDirectory = Join-Path $data 'Config'
$runKey = 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run'
$runValueName = if ($Component -eq 'Touch') { 'TG Exhibition Touch Launcher' } else { 'TG Exhibition Led Launcher' }
$runtimeConfigName = if ($Component -eq 'Touch') { 'touch-client.json' } else { 'led-player.json' }
$runtimeConfigPath = Join-Path $configDirectory $runtimeConfigName
$launcherConfigPath = Join-Path $configDirectory 'launcher.json'
$launcherExe = Join-Path $install 'Launcher\TG.Control.Launcher.exe'
$clientExe = if ($Component -eq 'Touch') {
    Join-Path $install 'TouchClient\TouchClient.exe'
} else {
    Join-Path $install 'LedPlayer\LedPlayer.exe'
}

function Assert-Administrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = [Security.Principal.WindowsPrincipal]::new($identity)
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw 'Installation must run from an elevated administrator process.'
    }
}

function Protect-MachineSecret([string]$value) {
    $clear = [Text.Encoding]::UTF8.GetBytes($value)
    $encrypted = [System.Security.Cryptography.ProtectedData]::Protect(
        $clear, $null, [System.Security.Cryptography.DataProtectionScope]::LocalMachine)
    return 'dpapi-local-machine:' + [Convert]::ToBase64String($encrypted)
}

function Write-Json([string]$path, [object]$value) {
    $json = $value | ConvertTo-Json -Depth 12
    $temporary = $path + '.tmp'
    [IO.File]::WriteAllText($temporary, $json, [Text.UTF8Encoding]::new($false))
    Move-Item -LiteralPath $temporary -Destination $path -Force
}

function Resolve-OptionalPath([string]$value, [string]$baseDirectory) {
    if ([string]::IsNullOrWhiteSpace($value)) { return $null }
    if ([IO.Path]::IsPathRooted($value)) { return [IO.Path]::GetFullPath($value) }
    return [IO.Path]::GetFullPath((Join-Path $baseDirectory $value))
}

Assert-Administrator
if (-not (Test-Path -LiteralPath $launcherExe -PathType Leaf)) { throw "Launcher executable is missing: $launcherExe" }
if (-not (Test-Path -LiteralPath $clientExe -PathType Leaf)) { throw "Client executable is missing: $clientExe" }

New-Item -ItemType Directory -Path $configDirectory,(Join-Path $data 'Logs\Launcher') -Force | Out-Null
if ($Component -eq 'Touch') { New-Item -ItemType Directory -Path (Join-Path $data 'Logs\TouchClient') -Force | Out-Null }
else {
    New-Item -ItemType Directory -Path (Join-Path $data 'Logs\LedPlayer'),(Join-Path $data 'Cache\LedPlayer\Content') -Force | Out-Null
}

$site = $null
if (-not [string]::IsNullOrWhiteSpace($SiteConfig) -and (Test-Path -LiteralPath $SiteConfig -PathType Leaf)) {
    # Windows PowerShell 5.1 otherwise decodes BOM-less UTF-8 as the active ANSI code page.
    $site = Get-Content -LiteralPath $SiteConfig -Raw -Encoding UTF8 | ConvertFrom-Json
}
if ($null -eq $site -and -not (Test-Path -LiteralPath $runtimeConfigPath -PathType Leaf)) {
    throw "First installation requires a site configuration file: $SiteConfig"
}

if ($null -ne $site) {
    $serverBaseUrl = ([string]$site.serverBaseUrl).TrimEnd('/')
    $terminalApiKey = [string]$site.terminalApiKey
    if ($serverBaseUrl.Contains([char]0xFF1A)) {
        throw 'serverBaseUrl contains a full-width Chinese colon. Use an ASCII colon, for example https://192.168.86.40:5443.'
    }
    $parsedServerUri = $null
    if (-not [Uri]::TryCreate($serverBaseUrl, [UriKind]::Absolute, [ref]$parsedServerUri) -or
        -not ($serverBaseUrl.StartsWith('https://', [StringComparison]::OrdinalIgnoreCase) -or
              $serverBaseUrl.StartsWith('http://', [StringComparison]::OrdinalIgnoreCase))) {
        throw 'serverBaseUrl must be an absolute HTTP or HTTPS address.'
    }
    if ([string]::IsNullOrWhiteSpace($terminalApiKey) -or $terminalApiKey -eq 'REPLACE_WITH_SERVER_ENROLLMENT_KEY') {
        throw 'terminalApiKey must match the enrollment key generated by the Server installer.'
    }

    $siteDirectory = Split-Path -Parent ([IO.Path]::GetFullPath($SiteConfig))
    $certificatePath = Resolve-OptionalPath ([string]$site.trustedCertificatePath) $siteDirectory
    if ($serverBaseUrl.StartsWith('https://', [StringComparison]::OrdinalIgnoreCase) -and
        -not [string]::IsNullOrWhiteSpace($certificatePath)) {
        if (-not (Test-Path -LiteralPath $certificatePath -PathType Leaf)) {
            throw "Trusted Server certificate was not found: $certificatePath"
        }
        Import-Certificate -FilePath $certificatePath -CertStoreLocation 'Cert:\LocalMachine\Root' | Out-Null
    }

    $protectedTerminalKey = Protect-MachineSecret $terminalApiKey
    if ($Component -eq 'Touch') {
        Write-Json $runtimeConfigPath ([ordered]@{
            serverBaseUrl = $serverBaseUrl; clientId = 'touch-main'; terminalApiKey = $protectedTerminalKey
        })
    } else {
        Write-Json $runtimeConfigPath ([ordered]@{
            serverBaseUrl = $serverBaseUrl; clientId = 'led-main'; terminalApiKey = $protectedTerminalKey
            cacheDirectory = (Join-Path $data 'Cache\LedPlayer\Content')
        })
    }
} else {
    $existing = Get-Content -LiteralPath $runtimeConfigPath -Raw | ConvertFrom-Json
    $serverBaseUrl = ([string]$existing.serverBaseUrl).TrimEnd('/')
}

$isTouch = $Component -eq 'Touch'
$touchClientExecutable = if ($isTouch) { $clientExe } else { '' }
$ledPlayerExecutable = if ($isTouch) { '' } else { $clientExe }
$touchClientConfiguration = if ($isTouch) { $runtimeConfigPath } else { '' }
$ledPlayerConfiguration = if ($isTouch) { '' } else { $runtimeConfigPath }
Write-Json $launcherConfigPath ([ordered]@{
    serverHealthUrl = "$serverBaseUrl/api/health"; adminUrl = "$serverBaseUrl/"
    touchClientExecutable = $touchClientExecutable
    ledPlayerExecutable = $ledPlayerExecutable
    touchClientConfiguration = $touchClientConfiguration
    ledPlayerConfiguration = $ledPlayerConfiguration
    touchClientLogFile = (Join-Path $data 'Logs\TouchClient\Player.log')
    ledPlayerLogFile = (Join-Path $data 'Logs\LedPlayer\Player.log')
    logDirectory = (Join-Path $data 'Logs\Launcher'); healthPollSeconds = 3
    clientRestartDelaySeconds = 5; enableTouchClient = $isTouch; enableLedPlayer = -not $isTouch
    showAdminButton = $isTouch; autoStartTouchClient = $isTouch; autoStartLedPlayer = -not $isTouch
    autoRestartClients = $true
})

& "$env:SystemRoot\System32\icacls.exe" $configDirectory '/inheritance:r' '/grant:r' `
    'SYSTEM:(OI)(CI)F' 'Administrators:(OI)(CI)F' 'Users:(RX)' | Out-Null
foreach ($name in @($runtimeConfigName, 'launcher.json')) {
    & "$env:SystemRoot\System32\icacls.exe" (Join-Path $configDirectory $name) `
        '/inheritance:r' '/grant:r' 'SYSTEM:F' 'Administrators:F' 'Users:R' | Out-Null
}
foreach ($writableName in @('Cache','Logs')) {
    $path = Join-Path $data $writableName
    if (Test-Path -LiteralPath $path) {
        & "$env:SystemRoot\System32\icacls.exe" $path '/inheritance:r' '/grant:r' `
            'SYSTEM:(OI)(CI)F' 'Administrators:(OI)(CI)F' 'Users:(OI)(CI)M' | Out-Null
    }
}

New-ItemProperty -Path $runKey -Name $runValueName -Value ('"' + $launcherExe + '"') -PropertyType String -Force | Out-Null
Write-Host "TG Exhibition $Component terminal configuration completed."
